# Configuration file to declaratively configure labels
# Ref: https://github.com/EndBug/label-sync#Config-files

- name: area/actions
  description: GitHub Actions related issues and pull requests
  color: '#00b140'
- name: area/artifact
  description: Artifact SDK related issues and pull requests
  color: '#006b75'
- name: area/git
  description: Git and SSH related issues and pull requests
  color: '#863faf'
- name: area/helm
  description: Helm related issues and pull requests
  color: '#1673b6'
- name: area/http
  description: HTTP transport related issues and pull requests
  color: '#006b75'
- name: area/oci
  description: OCI related issues and pull requests
  color: '#c739ff'
- name: area/kustomize
  description: Kustomize related issues and pull requests
  color: '#00e54d'
- name: area/runtime
  description: Controller runtime related issues and pull requests
  color: '#00e54d'
- name: area/server-side-apply
  description: SSA related issues and pull requests
  color: '#2819CB'
- name: area/testserver
  description: Test server related issues and pull requests
  color: '#006b75'
- name: backport:flux/v2.8.x
  description: To be backported to flux/v2.8.x
  color: '#ffd700'
