/*
Copyright 2026 The Flux authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package tar

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// ResolveSymlinks stages the contents of srcDir into dstDir, following
// every symlink and copying the target's contents. Both paths must be
// existing directories.
//
// Symlink cycles are detected and skipped. Non-regular, non-directory
// entries (devices, sockets, etc.) are skipped.
//
// This is a staging helper intended to be paired with Tar for inputs
// that contain symlinks (for example, manifest trees generated by Nix
// where the actual files live outside the source directory).
//
// Security: symlinks may point outside srcDir. Their targets are
// materialized in dstDir under the link's name. Only use with trusted
// input.
func ResolveSymlinks(srcDir, dstDir string) error {
	absSrc, err := filepath.Abs(srcDir)
	if err != nil {
		return err
	}
	realSrc, err := filepath.EvalSymlinks(absSrc)
	if err != nil {
		return fmt.Errorf("resolving srcDir: %w", err)
	}

	info, err := os.Stat(realSrc)
	if err != nil {
		return err
	}
	if !info.IsDir() {
		return fmt.Errorf("srcDir %s is not a directory", absSrc)
	}

	if err = checkDstDir(dstDir); err != nil {
		return err
	}

	return copyDir("", realSrc, dstDir, make(map[string]bool))
}

// ResolveSymlinksRoot is the confined variant of ResolveSymlinks: every
// symlink target must resolve within rootDir. A symlink whose final
// resolved path is outside rootDir causes the function to fail.
//
// srcDir must be within (or equal to) rootDir. dstDir is not required
// to be within rootDir.
//
// Symlink cycles are detected and skipped. Non-regular, non-directory
// entries are skipped.
//
// Note: containment is checked against the resolved absolute path, so
// intermediate "../" navigation within rootDir is allowed (common in
// Nix-style trees). Symlink resolution uses filepath.EvalSymlinks; this
// leaves a small TOCTOU window and should not be used to defend against
// an adversary with concurrent write access to the source tree.
func ResolveSymlinksRoot(rootDir, srcDir, dstDir string) error {
	absRoot, err := filepath.Abs(rootDir)
	if err != nil {
		return err
	}
	absSrc, err := filepath.Abs(srcDir)
	if err != nil {
		return err
	}

	realRoot, err := filepath.EvalSymlinks(absRoot)
	if err != nil {
		return fmt.Errorf("resolving rootDir: %w", err)
	}
	realSrc, err := filepath.EvalSymlinks(absSrc)
	if err != nil {
		return fmt.Errorf("resolving srcDir: %w", err)
	}

	if !isWithin(realRoot, realSrc) {
		return fmt.Errorf("srcDir %s is not within rootDir %s", absSrc, absRoot)
	}

	info, err := os.Stat(realSrc)
	if err != nil {
		return err
	}
	if !info.IsDir() {
		return fmt.Errorf("srcDir %s is not a directory", absSrc)
	}

	if err = checkDstDir(dstDir); err != nil {
		return err
	}

	return copyDir(realRoot, realSrc, dstDir, make(map[string]bool))
}

// checkDstDir verifies that dstDir exists and is a directory.
func checkDstDir(dstDir string) error {
	info, err := os.Stat(dstDir)
	if err != nil {
		return fmt.Errorf("stat dstDir: %w", err)
	}
	if !info.IsDir() {
		return fmt.Errorf("dstDir %s is not a directory", dstDir)
	}
	return nil
}

// copyDir recursively copies srcDir into dstDir, resolving all
// symlinks. srcDir must already be fully resolved (no symlink
// components). If confineRoot is non-empty, every symlink target must
// resolve within confineRoot; a violation fails the call. visited is a
// stack-based cycle breaker: directories currently on the call stack
// are skipped to prevent infinite loops from symlink cycles. Entries
// are removed when the call returns, so the same directory may be
// copied again through a different symlink — this is intentional
// (both link sites need the content).
func copyDir(confineRoot, srcDir, dstDir string, visited map[string]bool) error {
	if visited[srcDir] {
		return nil
	}
	visited[srcDir] = true
	defer delete(visited, srcDir)

	entries, err := os.ReadDir(srcDir)
	if err != nil {
		return err
	}

	for _, entry := range entries {
		srcPath := filepath.Join(srcDir, entry.Name())
		dstPath := filepath.Join(dstDir, entry.Name())

		isLink := entry.Type()&os.ModeSymlink != 0

		realPath := srcPath
		if isLink {
			realPath, err = filepath.EvalSymlinks(srcPath)
			if err != nil {
				return fmt.Errorf("resolving symlink %s: %w", srcPath, err)
			}
			// Report the logical path, not the resolved target,
			// to avoid leaking filesystem layout.
			if confineRoot != "" && !isWithin(confineRoot, realPath) {
				return fmt.Errorf("symlink %s resolves outside rootDir", srcPath)
			}
		}

		var realInfo os.FileInfo
		if isLink {
			realInfo, err = os.Stat(realPath)
		} else {
			realInfo, err = entry.Info()
		}
		if err != nil {
			return fmt.Errorf("stat %s: %w", realPath, err)
		}

		if realInfo.IsDir() {
			if err = os.MkdirAll(dstPath, realInfo.Mode()); err != nil {
				return err
			}
			if err = copyDir(confineRoot, realPath, dstPath, visited); err != nil {
				return err
			}
			continue
		}

		if !realInfo.Mode().IsRegular() {
			continue
		}

		if err = copyResolvedFile(realPath, dstPath, realInfo.Mode()); err != nil {
			return err
		}
	}
	return nil
}

// isWithin reports whether path is equal to or inside root. Both
// arguments should be absolute, cleaned paths; the caller is
// responsible for resolving symlinks in root ahead of time.
func isWithin(root, path string) bool {
	rel, err := filepath.Rel(root, path)
	if err != nil {
		return false
	}
	return rel != ".." && !strings.HasPrefix(rel, ".."+string(filepath.Separator))
}

// copyResolvedFile copies the contents of src to dst with the given
// mode. src is expected to be a regular file (EvalSymlinks'd by the
// caller) and filepath.Dir(dst) is expected to already exist — the
// walk creates each subdirectory via os.MkdirAll before descending, so
// the parent of dst is guaranteed to be present.
func copyResolvedFile(src, dst string, mode os.FileMode) (err error) {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer func() {
		if closeErr := in.Close(); closeErr != nil && err == nil {
			err = closeErr
		}
	}()

	out, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, mode)
	if err != nil {
		return err
	}
	defer func() {
		if closeErr := out.Close(); closeErr != nil && err == nil {
			err = closeErr
		}
	}()
	_, err = io.Copy(out, in)
	return err
}
