name: 'Run tests'
description: 'Run tests in docker container'
inputs:
  command:
    description: 'Command to run inside the container'
    required: true
    default: 'make all'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
