name: build

on:
  pull_request:
  push:
    branches:
      - main

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        chunk: ["1/4", "2/4", "3/4", "4/4"]
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: 1.26.x
          # https://github.com/actions/setup-go/blob/main/docs/adrs/0000-caching-dependencies.md#example-of-real-use-cases
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - name: Run tests (chunk ${{ matrix.chunk }})
        env:
          SKIP_COSIGN_VERIFICATION: true
        run: make test-chunk CHUNK=${{ matrix.chunk }}
      - name: Check if working tree is dirty
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            git --no-pager diff
            echo 'run make all and commit changes'
            exit 1
          fi
