name: preview-release

on:
  workflow_dispatch:

jobs:
  preview-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: cmd/go.mod
          cache-dependency-path: "**/go.sum"
      - run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git config --global user.name "github-actions[bot]"
      - run: make flux-tools
      - run: ./bin/flux-tools pkg prep --yes
      - run: git add .
      - run: git commit -m "Release preview" || true
      - run: ./bin/flux-tools pkg release --preview
